import {icon,hydrateIcons} from './icons.js';
export const $=(q,r=document)=>r.querySelector(q);export const $$=(q,r=document)=>[...r.querySelectorAll(q)];
export const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export function toast(title,text='',type=''){const stack=$('#toastStack');const el=document.createElement('div');el.className=`toast ${type}`;el.innerHTML=`<span>${icon(type==='success'?'check':type==='error'?'x':'bell')}</span><span class="toast-copy"><b>${esc(title)}</b>${text?`<span>${esc(text)}</span>`:''}</span>`;stack.append(el);setTimeout(()=>el.remove(),3400)}
export function openModal({title='Venster',eyebrow='GO',html=''}){$('#modalTitle').textContent=title;$('#modalEyebrow').textContent=eyebrow;$('#modalBody').innerHTML=html;$('#modalLayer').classList.add('open');$('#modalLayer').setAttribute('aria-hidden','false');hydrateIcons($('#modalLayer'));setTimeout(()=>$('input,button,select,textarea',$('#modalBody'))?.focus(),30)}
export function closeModal(){$('#modalLayer').classList.remove('open');$('#modalLayer').setAttribute('aria-hidden','true')}
export function openDrawer({title='Paneel',eyebrow='GO',html=''}){$('#drawerTitle').textContent=title;$('#drawerEyebrow').textContent=eyebrow;$('#drawerBody').innerHTML=html;$('#drawerLayer').classList.add('open');$('#drawerLayer').setAttribute('aria-hidden','false');hydrateIcons($('#drawerLayer'))}
export function closeDrawer(){$('#drawerLayer').classList.remove('open');$('#drawerLayer').setAttribute('aria-hidden','true')}
export function contextMenu(x,y,items=[]){const menu=$('#contextMenu');menu.innerHTML=items.map(item=>`<button type="button" data-menu-action="${esc(item.action)}" class="${item.danger?'danger':''}">${icon(item.icon||'grid')}<span>${esc(item.label)}</span></button>`).join('');menu.hidden=false;const w=210,h=Math.min(300,items.length*40+10);menu.style.left=`${Math.min(x,innerWidth-w-8)}px`;menu.style.top=`${Math.min(y,innerHeight-h-8)}px`;hydrateIcons(menu);return new Promise(resolve=>{const handler=e=>{const b=e.target.closest('[data-menu-action]');if(!b)return;cleanup();resolve(b.dataset.menuAction)};const outside=e=>{if(!menu.contains(e.target)){cleanup();resolve(null)}};function cleanup(){menu.hidden=true;menu.removeEventListener('click',handler);document.removeEventListener('pointerdown',outside,true)}menu.addEventListener('click',handler);setTimeout(()=>document.addEventListener('pointerdown',outside,true),0)})}
export function percent(a,b){return b?Math.round((a/b)*100):0}
export function formatDate(value){if(!value)return'Geen datum';const [y,m,d]=value.split('-').map(Number);return new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'short',year:'numeric'}).format(new Date(Date.UTC(y,m-1,d)))}
export function initials(name){return name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
export function pageHeader(title,subtitle,actions=''){return `<div class="page-head"><div class="page-title"><h1>${esc(title)}</h1>${subtitle?`<p>${esc(subtitle)}</p>`:''}</div><div class="page-actions">${actions}</div></div>`}
export function emptyState(iconName,title,text,action=''){return `<div class="empty"><div><div class="empty-icon">${icon(iconName)}</div><h3>${esc(title)}</h3><p>${esc(text)}</p>${action}</div></div>`}
