import {store,makeId} from './modules/store.js';
import {groups,locations,libraryApps} from './modules/data.js';
import {hydrateIcons,icon} from './modules/icons.js';
import {renderPage} from './modules/pages.js';
import {$,$$,esc,toast,openModal,closeModal,openDrawer,closeDrawer,contextMenu,formatDate,initials} from './modules/ui.js';

const page=$('#page');
const routeTitles={'my-apps':'Mijn applicaties','group-apps':'Groepsapplicaties',tasks:'Taken',classroom:'Klassenmanagement',library:'Bibliotheek',notifications:'Meldingen',settings:'Instellingen',help:'Help & informatie'};

function syncShell(state){
 const group=store.group(),location=store.location();
 $('#groupLabel').textContent=group.name;$('#groupMeta').textContent=`${group.count} leerlingen`;$('.group-avatar').textContent=group.short;
 $('#locationLabel').textContent=location.name;
 $('#taskCount').textContent=state.tasks.filter(t=>t.status==='open').length;
 $('#notificationCount').textContent=state.notifications.filter(n=>!n.read).length;
 $$('.nav-item[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));
 $('#breadcrumbs').innerHTML=`<span>GO</span><span>/</span><b>${esc(routeTitles[state.route]||'Mijn applicaties')}</b>`;
 document.title=`${routeTitles[state.route]||'GO'} · GO Docentportaal`;
}
function render(){const state=store.get();syncShell(state);page.innerHTML=renderPage(state);hydrateIcons(page);bindDrag();}
store.subscribe(render);render();hydrateIcons(document);

function go(route){store.route(route);$('#main').focus();document.querySelector('.app-shell').classList.remove('mobile-nav-open')}

document.addEventListener('click',async e=>{
 const route=e.target.closest('[data-route]');if(route){go(route.dataset.route);return}
 if(e.target.closest('[data-close-modal]')){closeModal();return}
 if(e.target.closest('[data-close-drawer]')){closeDrawer();return}
 const action=e.target.closest('[data-action]');if(!action)return;
 const id=action.dataset.id;
 switch(action.dataset.action){
  case'home':go('my-apps');break;
  case'new-app':showAppForm();break;
  case'favorite-app':{const app=store.get().apps.find(a=>a.id===id);if(app)store.patchApp(id,{favorite:!app.favorite});break}
  case'open-app':openApp(id);break;
  case'app-menu':await showAppMenu(action,id);break;
  case'add-library-app':addLibraryApp(action.dataset.libraryId);break;
  case'new-task':showTaskForm();break;
  case'open-task':showTaskDetails(id);break;
  case'task-menu':await showTaskMenu(action,id);break;
  case'task-library':showTaskLibrary();break;
  case'toggle-student':store.patchStudent(id,{selected:action.checked});break;
  case'select-all':store.selectAll(true);break;
  case'clear-selection':store.clearSelection();break;
  case'toggle-pause':togglePause(id);break;
  case'pause-selected':toggleSelectedPause();break;
  case'lock-selected':toggleSelectedLock();break;
  case'send-link':showSendLink();break;
  case'broadcast':showBroadcast();break;
  case'student-details':showStudentDetails(id);break;
  case'refresh-class':toast('Klassenmanagement vernieuwd','De demo-statussen zijn opnieuw geladen.','success');render();break;
  case'mark-read':store.update(s=>({...s,notifications:s.notifications.map(n=>({...n,read:true}))}));toast('Meldingen bijgewerkt','Alles is gemarkeerd als gelezen.','success');break;
  case'reset-demo':if(confirm('Alle lokale demo-aanpassingen wissen?')){store.reset();toast('Demo gereset','','success')}break;
 }
});

document.addEventListener('input',e=>{
 if(e.target.id==='appsSearch')store.ui('appQuery',e.target.value);
 if(e.target.id==='librarySearch')store.ui('libraryQuery',e.target.value);
});
document.addEventListener('change',e=>{
 if(e.target.matches('[data-setting]')){const key=e.target.dataset.setting;store.setting(key,e.target.type==='checkbox'?e.target.checked:e.target.value)}
});
document.addEventListener('click',e=>{
 const sort=e.target.closest('[data-app-sort]');if(sort)store.ui('appSort',sort.dataset.appSort);
 const tab=e.target.closest('[data-task-tab]');if(tab)store.ui('taskTab',tab.dataset.taskTab);
 const layout=e.target.closest('[data-class-layout]');if(layout)store.setting('classLayout',layout.dataset.classLayout);
});

$('#collapseSidebar').addEventListener('click',()=>{$('#app').classList.toggle('sidebar-collapsed')});
$('#mobileMenu').addEventListener('click',()=>{$('#app').classList.toggle('mobile-nav-open')});
$('#quickCreate').addEventListener('click',()=>openQuickCreate());
$('#notificationButton').addEventListener('click',()=>go('notifications'));
$('#locationSwitcher').addEventListener('click',()=>showLocationPicker());
$('#groupSwitcher').addEventListener('click',()=>showGroupPicker());
$('#profileButton').addEventListener('click',()=>showProfile());$('#topProfile').addEventListener('click',()=>showProfile());

function showLocationPicker(){openDrawer({title:'Locatie kiezen',eyebrow:'GO',html:`<div class="dropdown-list">${locations.map(l=>`<button class="dropdown-option ${store.get().locationId===l.id?'active':''}" data-location-id="${l.id}"><span class="empty-icon" style="width:38px;height:38px;margin:0">${icon('school')}</span><span class="copy"><b>${esc(l.name)}</b><small>${esc(l.sub)}</small></span></button>`).join('')}</div>`});$$('[data-location-id]',$('#drawerBody')).forEach(b=>b.addEventListener('click',()=>{store.setLocation(b.dataset.locationId);closeDrawer();toast('Locatie gewijzigd',b.textContent.trim(),'success')}))}
function showGroupPicker(){openDrawer({title:'Groep kiezen',eyebrow:'Klassen',html:`<div class="dropdown-list">${groups.map(g=>`<button class="dropdown-option ${store.get().groupId===g.id?'active':''}" data-group-id="${g.id}"><span class="group-avatar">${g.short}</span><span class="copy"><b>${esc(g.name)}</b><small>${g.count} leerlingen</small></span></button>`).join('')}</div>`});$$('[data-group-id]',$('#drawerBody')).forEach(b=>b.addEventListener('click',()=>{store.setGroup(b.dataset.groupId);closeDrawer();toast('Groep geopend',store.group().name,'success')}))}
function showProfile(){openDrawer({title:'Levi Docent',eyebrow:'Profiel',html:`<div style="display:grid;justify-items:center;text-align:center;gap:8px;padding:10px 0 22px"><span class="avatar" style="width:72px;height:72px;font-size:22px">LD</span><h3 style="margin:5px 0 0">Levi Docent</h3><span class="pill blue">Leerkracht</span></div><div class="card"><div class="card-body"><div class="field"><span class="field-label">Actieve locatie</span><b>${esc(store.location().name)}</b></div><div class="divider"></div><div class="field"><span class="field-label">Actieve groep</span><b>${esc(store.group().name)}</b></div></div></div>`})}
function openQuickCreate(){openModal({title:'Nieuw maken',eyebrow:'Snelmenu',html:`<div class="library-grid"><button class="card" data-quick="app" style="padding:18px;text-align:left;border:1px solid var(--line)"><div class="empty-icon">${icon('plus')}</div><b>Applicatie</b><p class="muted">Voeg een webapptegel toe.</p></button><button class="card" data-quick="task" style="padding:18px;text-align:left;border:1px solid var(--line)"><div class="empty-icon">${icon('check-square')}</div><b>Taak</b><p class="muted">Maak een nieuwe opdracht.</p></button><button class="card" data-quick="link" style="padding:18px;text-align:left;border:1px solid var(--line)"><div class="empty-icon">${icon('link')}</div><b>Weblink</b><p class="muted">Stuur een link naar leerlingen.</p></button></div>`});$$('[data-quick]',$('#modalBody')).forEach(b=>b.addEventListener('click',()=>{const type=b.dataset.quick;closeModal();if(type==='app')showAppForm();if(type==='task')showTaskForm();if(type==='link')showSendLink()}))}

function showAppForm(existing=null){const app=existing||{name:'',subtitle:'',url:'',initials:'',color:'logo-blue',group:false,favorite:false};openModal({title:existing?'Applicatie bewerken':'Applicatie toevoegen',eyebrow:'Applicaties',html:`<form id="appForm"><div class="form-grid"><div class="field full"><label>Naam</label><input class="input" name="name" required maxlength="40" value="${esc(app.name)}" placeholder="Bijv. Rekentuin"></div><div class="field full"><label>URL</label><input class="input" name="url" value="${esc(app.url||'')}" placeholder="https://..."></div><div class="field"><label>Ondertitel</label><input class="input" name="subtitle" maxlength="50" value="${esc(app.subtitle||'')}"></div><div class="field"><label>Letters / icoon</label><input class="input" name="initials" maxlength="3" value="${esc(app.initials||'')}"></div><div class="field"><label>Kleur</label><select class="select" name="color">${['logo-blue','logo-green','logo-purple','logo-orange','logo-red','logo-cyan','logo-dark','logo-yellow'].map(c=>`<option ${app.color===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Dashboard</label><select class="select" name="scope"><option value="mine" ${!app.group?'selected':''}>Mijn applicaties</option><option value="group" ${app.group?'selected':''}>Groepsapplicaties</option></select></div></div><div class="modal-actions"><button class="btn" type="button" data-close-modal>Annuleren</button><button class="btn primary" type="submit">Opslaan</button></div></form>`});$('#appForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),name=fd.get('name').trim();const patch={name,url:fd.get('url').trim()||'#',subtitle:fd.get('subtitle').trim()||'Webapplicatie',initials:fd.get('initials').trim()||initials(name).slice(0,2),color:fd.get('color'),group:fd.get('scope')==='group'};if(existing)store.patchApp(existing.id,patch);else store.addApp({id:makeId('app'),favorite:false,...patch});closeModal();toast(existing?'Applicatie bijgewerkt':'Applicatie toegevoegd',name,'success')})}
function openApp(id){const app=store.get().apps.find(a=>a.id===id);if(!app)return;if(app.url&&app.url!=='#'&&/^https?:\/\//i.test(app.url)){window.open(app.url,'_blank','noopener')}else toast(app.name,'Demo-tegel geopend. Koppel later de echte SSO/URL.','success')}
async function showAppMenu(button,id){const app=store.get().apps.find(a=>a.id===id);if(!app)return;const r=button.getBoundingClientRect();const action=await contextMenu(r.right,r.bottom,[{action:'edit',label:'Bewerken',icon:'edit'},{action:'favorite',label:app.favorite?'Favoriet verwijderen':'Favoriet maken',icon:'star'},{action:'remove',label:'Verwijderen',icon:'trash',danger:true}]);if(action==='edit')showAppForm(app);if(action==='favorite')store.patchApp(id,{favorite:!app.favorite});if(action==='remove'&&confirm(`${app.name} verwijderen?`)){store.removeApp(id);toast('Applicatie verwijderd',app.name,'success')}}
function addLibraryApp(id){const source=libraryApps.find(a=>a.id===id);if(!source)return;if(store.get().apps.some(a=>a.id===id)){toast('Staat al op je dashboard',source.name,'warning');return}store.addApp({...source,group:false,favorite:false,url:source.url||'#'});toast('Toegevoegd aan Mijn applicaties',source.name,'success')}

function showTaskForm(existing=null){const group=store.group();const t=existing||{title:'',summary:'',description:'',start:new Date().toISOString().slice(0,10),deadline:'',archive:'',feedback:false,notes:''};openModal({title:existing?'Taak bewerken':'Nieuwe taak',eyebrow:'Taken',html:`<form id="taskForm"><div class="wizard-steps"><i class="wizard-step active"></i><i class="wizard-step active"></i><i class="wizard-step"></i></div><div class="form-grid"><div class="field full"><label>Titel</label><input class="input" name="title" required maxlength="70" value="${esc(t.title)}" placeholder="Titel van de opdracht"></div><div class="field full"><label>Samenvatting</label><input class="input" name="summary" maxlength="120" value="${esc(t.summary)}"></div><div class="field full"><label>Beschrijving</label><textarea class="textarea" name="description">${esc(t.description)}</textarea></div><div class="field"><label>Startdatum</label><input class="input" type="date" name="start" value="${esc(t.start)}"></div><div class="field"><label>Deadline</label><input class="input" type="date" name="deadline" required value="${esc(t.deadline)}"></div><div class="field"><label>Archiefdatum</label><input class="input" type="date" name="archive" value="${esc(t.archive)}"></div><div class="field"><label>Voor wie?</label><select class="select" name="group"><option value="${group.id}">${esc(group.name)} (${group.count})</option></select></div><div class="field full"><label>Privénotities voor beheerders</label><textarea class="textarea" name="notes">${esc(t.notes||'')}</textarea></div><label class="checkbox-line full"><input type="checkbox" name="feedback" ${t.feedback?'checked':''}><span><b>Feedback vragen</b><br><small class="muted">Leerlingen kunnen aangeven hoe zij de taak hebben ervaren.</small></span></label></div><div class="modal-actions"><button class="btn" type="button" data-close-modal>Annuleren</button><button class="btn primary" type="submit">Taak opslaan</button></div></form>`});$('#taskForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),deadline=fd.get('deadline'),start=fd.get('start');const status=start>new Date().toISOString().slice(0,10)?'future':'open';const patch={title:fd.get('title').trim(),summary:fd.get('summary').trim(),description:fd.get('description').trim(),start,deadline,archive:fd.get('archive'),feedback:fd.get('feedback')==='on',notes:fd.get('notes').trim(),group:group.id,total:group.count,managers:['Levi Docent']};if(existing)store.patchTask(existing.id,patch);else store.addTask({id:makeId('task'),submitted:0,status,...patch});closeModal();toast(existing?'Taak bijgewerkt':'Taak aangemaakt',patch.title,'success')})}
function showTaskDetails(id){const t=store.get().tasks.find(x=>x.id===id);if(!t)return;openDrawer({title:t.title,eyebrow:'Taakdetails',html:`<div class="task-detail-head"><div><span class="pill ${t.status==='done'?'green':t.status==='future'?'orange':'blue'}">${t.status}</span><h3>${esc(t.title)}</h3><p class="muted">${esc(t.summary)}</p></div><button class="btn sm" id="editTask">${icon('edit')}Bewerken</button></div><div class="task-detail-block"><h4>Beschrijving</h4><p>${esc(t.description||'Geen beschrijving')}</p></div><div class="task-detail-block"><h4>Planning</h4><p>Start: <b>${formatDate(t.start)}</b><br>Deadline: <b>${formatDate(t.deadline)}</b><br>Archief: <b>${formatDate(t.archive)}</b></p></div><div class="task-detail-block"><h4>Voortgang</h4><div class="task-progress-line" style="width:100%"><div class="progress"><span style="width:${t.total?Math.round(t.submitted/t.total*100):0}%"></span></div><b>${t.submitted}/${t.total}</b></div></div>${t.notes?`<div class="task-detail-block"><h4>Privénotities</h4><p>${esc(t.notes)}</p></div>`:''}`});$('#editTask')?.addEventListener('click',()=>{closeDrawer();showTaskForm(t)})}
async function showTaskMenu(button,id){const task=store.get().tasks.find(t=>t.id===id);if(!task)return;const r=button.getBoundingClientRect();const a=await contextMenu(r.right,r.bottom,[{action:'view',label:'Openen',icon:'external'},{action:'edit',label:'Bewerken',icon:'edit'},{action:'complete',label:'Markeer afgerond',icon:'check'},{action:'delete',label:'Verwijderen',icon:'trash',danger:true}]);if(a==='view')showTaskDetails(id);if(a==='edit')showTaskForm(task);if(a==='complete')store.patchTask(id,{status:'done',submitted:task.total});if(a==='delete'&&confirm('Taak verwijderen?'))store.removeTask(id)}
function showTaskLibrary(){openDrawer({title:'Takenbibliotheek',eyebrow:'Herbruikbare opdrachten',html:`<div class="dropdown-list">${['Weektaak rekenen','Leesopdracht','Woordenschat oefenen','Presentatie voorbereiden'].map((x,i)=>`<button class="dropdown-option" data-template="${i}"><span class="empty-icon" style="width:38px;height:38px;margin:0">${icon('check-square')}</span><span class="copy"><b>${x}</b><small>Voorbeeldsjabloon</small></span></button>`).join('')}</div>`});$$('[data-template]',$('#drawerBody')).forEach(b=>b.addEventListener('click',()=>{closeDrawer();showTaskForm({title:b.textContent.trim(),summary:'Herbruikbare opdracht uit de bibliotheek.',description:'Pas deze beschrijving aan voor jouw les.',start:new Date().toISOString().slice(0,10),deadline:'',archive:'',feedback:true,notes:''})}))}

function togglePause(id){const s=store.get().students.find(x=>x.id===id);if(!s||s.status==='offline')return;store.patchStudent(id,{paused:!s.paused});toast(s.paused?'Device hervat':'Device gepauzeerd',`${s.name} · visuele simulatie`,'success')}
function toggleSelectedPause(){const list=store.get().students.filter(s=>s.selected&&s.status!=='offline');if(!list.length)return toast('Selecteer eerst leerlingen','','warning');const allPaused=list.every(s=>s.paused);store.patchSelected({paused:!allPaused});toast(allPaused?'Devices hervat':'Devices gepauzeerd',`${list.length} leerlingen · simulatie`,'success')}
function toggleSelectedLock(){const list=store.get().students.filter(s=>s.selected&&s.status!=='offline');if(!list.length)return toast('Selecteer eerst leerlingen','','warning');const allLocked=list.every(s=>s.locked);store.patchSelected({locked:!allLocked});toast(allLocked?'Tabbladen ontgrendeld':'Tabbladen vastgezet',`${list.length} leerlingen · simulatie`,'success')}
function showSendLink(){const selected=store.get().students.filter(s=>s.selected&&s.status!=='offline');openModal({title:'Weblink sturen',eyebrow:'Klassenmanagement',html:`<form id="linkForm"><div class="field"><label>Webadres</label><input class="input" name="url" type="url" required placeholder="https://..."></div><div class="field" style="margin-top:12px"><label>Ontvangers</label><select class="select" name="scope"><option value="selected" ${selected.length?'':'disabled'}>Geselecteerde leerlingen (${selected.length})</option><option value="online">Alle online leerlingen</option></select></div><label class="checkbox-line" style="margin-top:14px"><input type="checkbox" name="lock"><span><b>Direct vastzetten</b><br><small class="muted">Toon de link als gelockt tabblad in de simulatie.</small></span></label><div class="modal-actions"><button class="btn" type="button" data-close-modal>Annuleren</button><button class="btn primary" type="submit">Sturen</button></div></form>`});$('#linkForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget),url=fd.get('url'),lock=fd.get('lock')==='on',scope=fd.get('scope');store.update(s=>({...s,students:s.students.map(st=>{const target=scope==='online'?st.status!=='offline':st.selected;return target?{...st,tab:url.replace(/^https?:\/\//,'').slice(0,40),url,locked:lock}:st})}));closeModal();toast('Weblink verzonden',scope==='online'?'Naar alle online leerlingen':`Naar ${selected.length} geselecteerde leerlingen`,'success')})}
function showBroadcast(){openModal({title:'Scherm delen',eyebrow:'Klassenmanagement',html:`<div class="broadcast-card"><h4>Live scherm delen — demo</h4><p>In deze GitHub Pages-versie wordt alleen de workflow gesimuleerd. Een echte implementatie heeft een device-agent/extensie en backendverbinding nodig.</p></div><div class="field" style="margin-top:16px"><label>Ontvangers</label><select class="select" id="broadcastScope"><option>Alle online leerlingen</option><option>Alleen geselecteerde leerlingen</option></select></div><div class="modal-actions"><button class="btn" type="button" data-close-modal>Annuleren</button><button class="btn primary" id="startBroadcast">${icon('cast')}Delen starten</button></div>`});$('#startBroadcast').addEventListener('click',()=>{closeModal();toast('Schermdelen gestart','Visuele simulatie actief.','success')})}
function showStudentDetails(id){const s=store.get().students.find(x=>x.id===id);if(!s)return;openDrawer({title:s.name,eyebrow:'Leerlingdevice',html:`<div class="live-preview"><div class="mock-browser"><div class="mock-browser-top"><i></i><i></i><i></i><span class="mock-url"></span></div><div class="mock-page"><span class="mock-sidebar"></span><span class="mock-content"><i></i><i></i><i></i><i></i></span></div></div></div><div class="task-detail-block"><h4>Huidige activiteit</h4><p><b>${esc(s.tab)}</b><br>${esc(s.url)}</p></div><div class="task-detail-block"><h4>Status</h4><p>${s.status} · batterij ${s.battery}% · ${s.lastSeen}</p></div><div class="toolbar"><button class="btn" id="detailPause">${s.paused?icon('play'):icon('pause')}${s.paused?'Doorgaan':'Pauzeren'}</button><button class="btn" id="detailLock">${s.locked?icon('unlock'):icon('lock')}${s.locked?'Ontgrendelen':'Vastzetten'}</button></div>`});$('#detailPause').addEventListener('click',()=>{togglePause(id);closeDrawer()});$('#detailLock').addEventListener('click',()=>{store.patchStudent(id,{locked:!s.locked});closeDrawer();toast('Tabbladstatus aangepast',`${s.name} · simulatie`,'success')})}

function bindDrag(){const tiles=$$('.app-tile[data-app-id]');let dragged=null;tiles.forEach(tile=>{tile.addEventListener('dragstart',()=>{dragged=tile.dataset.appId;tile.classList.add('dragging')});tile.addEventListener('dragend',()=>{tile.classList.remove('dragging');$$('.drop-target').forEach(x=>x.classList.remove('drop-target'));dragged=null});tile.addEventListener('dragover',e=>{e.preventDefault();if(dragged&&dragged!==tile.dataset.appId)tile.classList.add('drop-target')});tile.addEventListener('dragleave',()=>tile.classList.remove('drop-target'));tile.addEventListener('drop',e=>{e.preventDefault();const target=tile.dataset.appId;if(!dragged||dragged===target)return;store.update(s=>{const arr=[...s.apps],from=arr.findIndex(a=>a.id===dragged),to=arr.findIndex(a=>a.id===target);const [item]=arr.splice(from,1);arr.splice(to,0,item);return{...s,apps:arr}});toast('Volgorde aangepast','','success')})})}

const globalSearch=$('#globalSearch');globalSearch.addEventListener('focus',()=>openCommands(globalSearch.value));globalSearch.addEventListener('input',()=>openCommands(globalSearch.value));
function openCommands(q=''){const state=store.get(),query=q.toLowerCase();const commands=[...Object.entries(routeTitles).map(([route,label])=>({label,route,icon:'grid'})),...state.apps.map(a=>({label:a.name,app:a.id,icon:'external'})),...state.tasks.map(t=>({label:t.title,task:t.id,icon:'check-square'}))].filter(x=>x.label.toLowerCase().includes(query)).slice(0,12);$('#commandPalette').hidden=false;$('#commandInput').value=q;$('#commandResults').innerHTML=commands.map((c,i)=>`<button class="command-item ${i===0?'active':''}" data-command-index="${i}"><span>${icon(c.icon)}</span><b>${esc(c.label)}</b><small>${c.route?'Pagina':c.app?'App':'Taak'}</small></button>`).join('');hydrateIcons($('#commandPalette'));$$('[data-command-index]',$('#commandResults')).forEach((b,i)=>b.addEventListener('click',()=>runCommand(commands[i])))}
function runCommand(c){$('#commandPalette').hidden=true;globalSearch.blur();if(c.route)go(c.route);if(c.app)openApp(c.app);if(c.task){go('tasks');setTimeout(()=>showTaskDetails(c.task),0)}}
$('#commandInput').addEventListener('input',e=>openCommands(e.target.value));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeDrawer();$('#commandPalette').hidden=true}if(e.key==='/'&&!/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)){e.preventDefault();globalSearch.focus()}});
$('#commandPalette').addEventListener('click',e=>{if(e.target===$('#commandPalette'))$('#commandPalette').hidden=true});
